DELIMITER //

CREATE TRIGGER prevent_reserv_boat_103
BEFORE INSERT ON BOATS
FOR EACH ROW
BEGIN
    IF NEW.AGE<18 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'AGE LESS THAN 18';
    END IF;
END; //

DELIMITER ;
